### ISSUE TITLE
Issue with draw_graph method

### ISSUE THREAD

**Issue by nickchak21** [brandones/graphpca#3]
I tried calling `graphpca.draw_graph(G)` for my graph. I got the following error (stack trace is below).

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    graphpca.draw_graph(G)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/graphpca/__init__.py", line 317, in draw_graph
    plt.plot([reduced_2[0, edge[0]], reduced_2[0, edge[1]]],
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

My guess is that you need to replace the commas you included with slices (`:`), but you should make sure this is the case.

**Comment by brandones** [comment]
I just upgraded to support NetworkX 2.x. I had written this for NetworkX 1.x, but (foolishly) not done any explicit dependency versioning.

Please install version 1.0.0 and try again. If you run into problems again, please provide the code you used to produce the graph.
